# Generated by Django 4.0.1 on 2022-02-24 06:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product', to='subscription.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('transaction_code', models.BigIntegerField()),
                ('applied_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('monthly_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tenor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan', to='subscription.product')),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(max_length=200)),
                ('transaction_code', models.BigIntegerField()),
                ('transaction_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction', to='subscription.loan')),
            ],
        ),
        migrations.CreateModel(
            name='ConsolidatedLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('transaction_date', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('narration', models.CharField(max_length=400)),
                ('transaction_code', models.BigIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consolidatedloan', to='subscription.loan')),
            ],
        ),
    ]
