# Generated by Django 4.0.1 on 2022-02-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(max_length=200)),
                ('transaction_code', models.BigIntegerField()),
                ('transaction_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='subscription.loan')),
            ],
        ),
        migrations.RemoveField(
            model_name='consolidatedloan',
            name='loan',
        ),
        migrations.AddField(
            model_name='consolidatedloan',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='consolidatedloan',
            name='transaction_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Deduction',
        ),
    ]
