# Generated by Django 4.0.1 on 2022-02-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_loandeduction_remove_consolidatedloan_loan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDeductionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_sum', models.DecimalField(decimal_places=2, max_digits=50)),
                ('transaction_code', models.BigIntegerField()),
                ('transaction_narration', models.CharField(max_length=200)),
                ('transaction_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='consolidatedloan',
            name='transaction_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
