# Generated by Django 4.0.1 on 2022-02-01 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='reference',
        ),
    ]
