# Generated by Django 4.0.1 on 2022-03-03 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0003_loandeductionsummary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandeduction',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loandeduction',
            name='loandeduction_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loandeductionuser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loandeductionsummary',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loandeductionsummary',
            name='cumulative_sum',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loandeduction',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loandeduction', to='subscription.loan'),
        ),
    ]
