# Generated by Django 4.0.1 on 2022-03-07 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0005_consolidatedloan_consolidatedloan_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loanuser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
