# Generated by Django 4.0.1 on 2022-03-08 15:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscription', '0008_remove_loan_created_by_remove_loan_loan_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('transaction_code', models.BigIntegerField()),
                ('applied_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('monthly_deduction', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tenor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(36)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loan', to='subscription.product')),
            ],
        ),
    ]
